name: Test Project
on: [push, workflow_dispatch]
jobs: 
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install golang
        uses: actions/setup-go@v3
      - name: Run linter 
        run: test -z "$(gofmt -l .)"
  test:
    needs: lint
    runs-on: ubuntu-22.04
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install golang
        uses: actions/setup-go@v3
      - name: Test
        run: go test
  build:
    needs: test
    runs-on: ubuntu-22.04
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install golang
        uses: actions/setup-go@v3
      - name: Build
        run: go build
