name: Test Project
on: 
  push:
  workflow_dispatch:
jobs: 
  output:
    runs-on: ubuntu-22.04
    steps:
      - name: Output event
        run: echo "${{ toJson(github.event) }}"
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install golang
        uses: actions/setup-go@v3
      - name: Lint code
        run: test -z "$(gofmt -l .)"
  test:
    needs: lint
    runs-on: ubuntu-22.04
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install golang
        uses: actions/setup-go@v3
      - name: Run tests
        run: go test
  build:
    needs: test
    runs-on: ubuntu-22.04
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install golang
        uses: actions/setup-go@v3
      - name: Build
        run: go build
